name: Terraform AWS EC2 and AWS ELB

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  test:
    defaults:
      run:
        working-directory: ./aws_ec2_elb
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: {
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
      }
    steps:
       - name: Checkout the repo 
         uses: actions/checkout@v4

       - name: Configure AWS Credentials
         run: |
           echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
           echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
       
       - name: Terraform fmt
         id: fmt
         run: |
           terraform fmt -check

       - name: Terraform Init
         id: init
         run: |
           terraform init
       
       - name: Terraform Validate
         id: validate
         run: |
           terraform validate

       - name: Terraform Plan
         id: plan
         run: |
           terraform plan
       
       - name: Terraform Plan Check
         if: steps.plan.outcome == 'failure'
         run: exit 1
