name: Terraform AWS EC2 and AWS ELB

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


env:
    # verbosity setting for Terraform logs
    TF_LOG: INFO
    # Credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: {
        dir: ["./aws_ec2_elb", "./aws_iam", "./aws_lambda_asg", "./aws_ec2_s3", "./gcp_vm_bucket"],
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
      }
    steps:
       - name: Checkout the repo 
         uses: actions/checkout@v4

       - name: Google Cloud Auth Service Account
         uses: google-github-actions/auth@v2
         with:
           credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

       - name: Setup Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v2

       - name: Use GCloud CLI
         run: |
           gcloud info

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
       
       - name: Terraform fmt
         id: fmt
         run: |
           terraform fmt -check

       - name: Terraform Init
         id: init
         run: |
           terraform init
       
       - name: Terraform Validate
         id: validate
         run: |
           terraform validate

       - name: Terraform Plan
         id: plan
         run: |
           terraform plan
       
       - name: Terraform Plan Check
         if: steps.plan.outcome == 'failure'
         run: exit 1
